services:
  - type: web
    name: kitchenos-backend
    env: python
    rootDir: backend_django
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn kitchenos.wsgi:application --preload --log-file - --log-level info
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kitchenos.settings_prod
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-service-name.onrender.com
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-vercel-app.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://your-vercel-app.vercel.app
